export const LOGIN_ATTEMPT = 'login_attempt'
export const LOGIN_SUCCESS = 'login_success'
export const LOGIN_FAILED = 'login_failed'
export const TOKEN_VALID = 'token-valid'
export const TOKEN_INVALID = 'token-invalid'